defaults: &defaults
  CONSUMER_KEY: '1XJfFTrHBj2nq7ZXubMHXqLLn' # API KEY
  CONSUMER_SECRET: 'SQEfByE8SNTscXQsR64sUz44CLk2fmOHJ8s96z9mRPzhAdwPp2' # API KEY SECRET
  ACCESS_TOKEN: '1454304963027292165-z6VctgG5tVsxci9VOxYZgBB6xg8mKx'
  ACCESS_TOKEN_SECRET: 'UIOFjNXrNYbUfEeBLZwKz9Kt21nNXNK4sMNRHiWRLcbzY'

production:
  <<: *defaults